version: 0.2

phases:
  pre_build:
    commands:
      - echo "Building java web application"
      
  build:
    commands:
      - mvn clean install
      
  post_build:
    commands:
      - echo "Build complete"
      
artifacts:
  files:
    - target/java-web-app.war
